FROM python:3.11-slim

# System vorbereiten
WORKDIR /app
ENV PYTHONUNBUFFERED=1

# System-Tools installieren & uv
RUN apt-get update && apt-get install -y curl && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Projektdateien kopieren, see .dockerignore
COPY . .

# .venv erstellen & dependencies installieren
RUN /root/.local/bin/uv venv && \
    /root/.local/bin/uv sync --python .venv/bin/python --no-cache

# Port öffnen
EXPOSE 8080

# Anwendung starten mit .venv aktivem Interpreter
CMD ["/app/.venv/bin/uvicorn", "{{ module_name }}.main:app", "--host", "0.0.0.0", "--port", "8080", "--log-level", "info"]
